# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xhw2rpdY_afk1lJyE16pprTO4MIVBqT7
"""

!pip install forex_python
from forex_python.converter import CurrencyRates
c = CurrencyRates()
amount=float(input("Enter the amount in USD:"))
target_currency=input("Enter currency code(e.g.EUR,IRR,GBP):").upper()

try:
  rate=c.get_rate('USD',target_currency)
  converted=c.convert('USD',target_currency,amount)
  print(f"\nExchange rate:1 USD={rate:4f} {target_currency}")
  print(f"{amount} USD={converted:.2f} {target_currency}")
except Exception as e:
  print(f"Error:", e)

import requests
api_key="c75a242e86064051ee819a12"
base_currency ="USD"
target_currency=input("Enter target currency code(e.g.EUR,IRR,GBP):").upper()
ur1= f"https://v6.exchangerate-api.com/v6/{api_key}/latest/{base_currency}"
Response=requests.get(ur1)
data=Response.json()
if target_currency in data["conversion_rates"]:
  rate=data["conversion_rates"][target_currency]
  amount=float(input(f"How much {base_currency} do you want to convert?"))
  converted= rate* amount
  print(f"\nExchange Rate: 1 {base_currency}={rate} {target_currency}")
  print(f"{amount} {base_currency}= {converted:.2f} {target_currency}")
else:
  print("currency code not found or invalid.")