# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rN-9siemlo28nDP12H9yYu_dOCG3aeZC
"""

import matplotlib.pyplot as plt
days= ['sat', 'sun' ,'mon','Tue','wen' , 'thu','fri']
exchang_rates = [0.92, 0.93 , 0.91 , 0.94, 0.95, 0.93 , 0.92]
plt.figure(figsize=(8,5))
plt.plot(days, exchang_rates, marker='o', color='blue')
plt.title('USD to EUR Echange Rate over a week')
plt.xlabel('Days')
plt.ylabel('Exchange Rate')
plt.grid(True)
plt.show()