# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WU8AGQqq6mAResShP1PW3_UTLMeEDGTB
"""

print("welcome to currency converter")
print("supported currencies :USD,EUR,IRR")
from_currency=input("from currency").upper()
to_currency=input("to currency:").upper()
amount_input=input("amount:")
if not amount_input.replace(".","",1).isdigit():
    print("please enter a valid number.")
else:
    amount=float(amount_input)
    rates={
        'USD':1.0,
        'EUR':0.9,
        'IRR':50000
    }
    if from_currency not in rates or to_currency not in rates:
        print("unsupported currency")
    else:
        usd_amount=amount/rates[from_currency]
        converted=usd_amount*rates[to_currency]
        print(f"{amount} {from_currency} = {converted:.2f} {to_currency}")